</td></tr>
</table>
</center>

</td>
<td width="250px" valign="top" align="left" bgcolor="#000000">
<!--NEWS-->
<br>
<center>
<table width="215px" cellspacing="3px" cellpadding="0px" border="0px">
<tr><td valign="top" align="left">
<iframe src="updates.html" name="updates" width="100%" height="100%" frameborder="no" noresize="true" scrolling="no" marginwidth="0px" marginheight="0px"></iframe>
</td></tr>
<tr><td valign="top" align="left">
<br><br><br>
<font face="verdana" color="#ffffff" size="1">
<b>Meetings this week (4/3):</b><br>
Tuesday:  <i>UC Caffee</i><br>
Wednesday:  <i>UC Caffee</i><br>
Times:  <i>6:30pm - 9:30pm</i>
</font>
</td></tr>

</table>
<br>
</center>

</td>
</tr>
</table>
</body>
</html>
