<html>
<head>
<title>CMU Chess Club</title>

<link rel="stylesheet" href="/inc/style.css" type="text/css">
</head>

<body bgcolor="#660000" text="#000000">
<table width="900px" bgcolor="#660000" cellpadding="0px" cellspacing="5px" border="0px">
<tr><td colspan="3" valign="top" align="left" bgcolor="#ffffff">

<img src="/imgs/main.png" border="0px"></td></tr>

<tr><td width="200px" valign="top" align="left" bgcolor="#000000">
<!--NAV BAR-->
<br><br>
<center>
<table width="120px" cellpadding="0px" cellspacing="0px" border="0px">
<tr><td valign="top" align="left">
<iframe src="/nav.html" name="nav" width="100%" height="100%" frameborder="no" noresize="true" scrolling="no" marginwidth="0px" marginheight="0px"></iframe>
</td></tr></table>
</center>
</td>
<td width="450px" valign="top" align="left" bgcolor="#ffffff">
<!--CONTENT-->
<br>
<center>
<table width="450px" border="0px" align="left" cellpadding="20px" cellspacing="0px">
<tr><td valign="top" align="left">
